
# S3 Images Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[security]
  [security.http]
    urls = ['.*']
    
[caches]
  [caches.images]
    dir = ':cacheDir/_gen'
    maxAge = '24h'
    
[imaging]
  quality = 85
  resampleFilter = 'lanczos'
  anchor = 'smart'

